// <auto-generated />
using System.Collections.Generic;
using Editor;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Editor.Migrations.Grammar
{
    [DbContext(typeof(GrammarDbContext))]
    [Migration("20260704211118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Editor.Form", b =>
                {
                    b.Property<string>("NormalizedForm")
                        .HasColumnType("text")
                        .HasColumnName("normalized_form");

                    b.Property<int>("ParadigmId")
                        .HasColumnType("integer")
                        .HasColumnName("paradigm_id");

                    b.Property<string>("VariantId")
                        .HasColumnType("text")
                        .HasColumnName("variant_id");

                    b.Property<string>("FormTag")
                        .HasColumnType("text")
                        .HasColumnName("form_tag");

                    b.HasKey("NormalizedForm", "ParadigmId", "VariantId", "FormTag")
                        .HasName("pk_forms");

                    b.ToTable("forms", (string)null);
                });

            modelBuilder.Entity("Editor.Paradigm", b =>
                {
                    b.Property<int>("ParadigmId")
                        .HasColumnType("integer")
                        .HasColumnName("paradigm_id");

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lemma");

                    b.Property<string>("Meaning")
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<List<ParadigmVariant>>("Variants")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variants");

                    b.HasKey("ParadigmId")
                        .HasName("pk_paradigms");

                    b.ToTable("paradigms", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
