// <auto-generated />
using System;
using Editor.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Editor.DB.Migrations.Grammar
{
    [DbContext(typeof(GrammarDbContext))]
    [Migration("20260911231238_AddParadigmCopyOrigin")]
    partial class AddParadigmCopyOrigin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("local_paradigm_id_seq")
                .StartsAt(1000000000L);

            modelBuilder.Entity("Editor.Domain.Grammar.Form", b =>
                {
                    b.Property<string>("NormalizedForm")
                        .HasColumnType("text")
                        .HasColumnName("normalized_form");

                    b.Property<int>("ParadigmId")
                        .HasColumnType("integer")
                        .HasColumnName("paradigm_id");

                    b.Property<string>("VariantId")
                        .HasColumnType("text")
                        .HasColumnName("variant_id");

                    b.Property<string>("FormTag")
                        .HasColumnType("text")
                        .HasColumnName("form_tag");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("source");

                    b.HasKey("NormalizedForm", "ParadigmId", "VariantId", "FormTag")
                        .HasName("pk_forms");

                    b.HasIndex("NormalizedForm")
                        .HasDatabaseName("ix_forms_normalized_form");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedForm"), new[] { "text_pattern_ops" });

                    b.ToTable("forms", (string)null);
                });

            modelBuilder.Entity("Editor.Domain.Grammar.HiddenParadigm", b =>
                {
                    b.Property<int>("ParadigmId")
                        .HasColumnType("integer")
                        .HasColumnName("paradigm_id");

                    b.Property<DateTime>("HiddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hidden_at");

                    b.Property<string>("HiddenBy")
                        .HasColumnType("text")
                        .HasColumnName("hidden_by");

                    b.HasKey("ParadigmId")
                        .HasName("pk_hidden_paradigms");

                    b.ToTable("hidden_paradigms", (string)null);
                });

            modelBuilder.Entity("Editor.Domain.Grammar.Paradigm", b =>
                {
                    b.Property<int>("ParadigmId")
                        .HasColumnType("integer")
                        .HasColumnName("paradigm_id");

                    b.Property<int?>("CopiedFromParadigmId")
                        .HasColumnType("integer")
                        .HasColumnName("copied_from_paradigm_id");

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lemma");

                    b.Property<string>("LemmaNormalized")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lemma_normalized");

                    b.Property<string>("Meaning")
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<int>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("source");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<string>("Variants")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variants");

                    b.HasKey("ParadigmId")
                        .HasName("pk_paradigms");

                    b.HasIndex("LemmaNormalized")
                        .HasDatabaseName("ix_paradigms_lemma_normalized");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("LemmaNormalized"), new[] { "text_pattern_ops" });

                    b.ToTable("paradigms", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
